#!/usr/bin/env bash
# install-shim.sh - Install the croam claude shim.
#
# Renames the system `claude` binary to `claude-real` and writes a wrapper
# that execs `croam launch "$@"`.  Supports --self-check, --uninstall, --help.
# Never calls sudo. Idempotent. Atomic via EXIT trap.
#
# Usage:
#   install-shim.sh             Install the shim.
#   install-shim.sh --self-check   Verify prerequisites, exit 0 if ok.
#   install-shim.sh --uninstall    Remove the shim, restore original binary.
#   install-shim.sh --help         Print this help.

set -euo pipefail

WRAPPER_MARKER="croam launch"

usage() {
    cat <<'EOF'
usage: install-shim.sh [--self-check | --uninstall | --help]

  (no args)     Rename system claude to claude-real; install croam wrapper.
  --self-check  Verify prerequisites without making changes. Exit 0 if ok.
  --uninstall   Reverse the install: rename claude-real back to claude.
  --help        Show this message.

Never calls sudo. Operates on the directory that contains the `claude` binary.
EOF
}

find_claude() {
    command -v claude 2>/dev/null || true
}

find_claude_real() {
    command -v claude-real 2>/dev/null || true
}

self_check() {
    local failures=0

    # Check claude on PATH.
    local claude_path
    claude_path=$(find_claude)
    if [ -z "$claude_path" ]; then
        echo "[FAIL] claude not found on PATH"
        failures=$((failures + 1))
    else
        echo "[OK] claude on PATH ($claude_path)"
    fi

    # Check croam on PATH.
    local croam_path
    croam_path=$(command -v croam 2>/dev/null || true)
    if [ -z "$croam_path" ]; then
        echo "[FAIL] croam not found on PATH"
        failures=$((failures + 1))
    else
        echo "[OK] croam on PATH ($croam_path)"
    fi

    if [ "$failures" -gt 0 ]; then
        exit 1
    fi
    exit 0
}

is_wrapper() {
    local path="$1"
    # Check it is a shell script that contains the croam launch marker.
    if ! file "$path" 2>/dev/null | grep -q "shell script"; then
        return 1
    fi
    if ! grep -q "$WRAPPER_MARKER" "$path" 2>/dev/null; then
        return 1
    fi
    return 0
}

install_shim() {
    local claude_path
    claude_path=$(find_claude)

    if [ -z "$claude_path" ]; then
        echo "ERROR: 'claude' not found on PATH. Install claude first." >&2
        exit 1
    fi

    local bin_dir
    bin_dir=$(dirname "$claude_path")

    # Check directory is writable without sudo.
    if [ ! -w "$bin_dir" ]; then
        echo "ERROR: $bin_dir is not writable. Cannot install shim without sudo." >&2
        echo "Hint: install croam into a user-writable prefix (e.g. ~/.local/bin) and" >&2
        echo "ensure that prefix is on PATH before the system prefix." >&2
        exit 1
    fi

    local real_path="$bin_dir/claude-real"
    local wrapper_path="$bin_dir/claude"

    # Idempotency: if wrapper is already in place, nothing to do.
    if is_wrapper "$wrapper_path" 2>/dev/null; then
        echo "Shim already installed at $wrapper_path (no-op)."
        exit 0
    fi

    # Atomic install: use an EXIT trap so that if the wrapper write fails
    # after the rename, we roll back.
    local rolled_back=0
    cleanup() {
        if [ "$rolled_back" -eq 0 ] && [ -f "$real_path" ] && [ ! -f "$wrapper_path" ]; then
            mv "$real_path" "$wrapper_path" 2>/dev/null || true
        fi
    }
    trap cleanup EXIT

    # Rename original claude -> claude-real.
    mv "$wrapper_path" "$real_path"

    # Write the wrapper.
    cat > "$wrapper_path" <<'WRAPPER'
#!/usr/bin/env bash
# Auto-generated by croam install-shim.sh. Do not edit.
exec croam launch "$@"
WRAPPER

    chmod +x "$wrapper_path"

    # Commit: signal that the wrapper was written successfully so the trap
    # does not roll back.
    rolled_back=1
    trap - EXIT

    echo "Installed: $real_path (original) and $wrapper_path (croam shim)."
}

uninstall_shim() {
    local real_path
    real_path=$(find_claude_real)

    if [ -z "$real_path" ]; then
        echo "Nothing to uninstall: 'claude-real' not found on PATH."
        exit 0
    fi

    local bin_dir
    bin_dir=$(dirname "$real_path")
    local wrapper_path="$bin_dir/claude"

    if [ ! -w "$bin_dir" ]; then
        echo "ERROR: $bin_dir is not writable. Cannot uninstall shim without sudo." >&2
        exit 1
    fi

    # Remove the wrapper (if it is one).
    if [ -f "$wrapper_path" ] && is_wrapper "$wrapper_path" 2>/dev/null; then
        rm "$wrapper_path"
    fi

    # Rename claude-real back to claude.
    mv "$real_path" "$wrapper_path"

    echo "Uninstalled: restored $wrapper_path from $real_path."
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

case "${1:-}" in
    --help|-h)
        usage
        exit 0
        ;;
    --self-check)
        self_check
        ;;
    --uninstall)
        uninstall_shim
        ;;
    "")
        install_shim
        ;;
    *)
        echo "Unknown argument: $1" >&2
        usage >&2
        exit 1
        ;;
esac
